### ISSUE TITLE
`const` breaks older versions of IE

### ISSUE THREAD

**Issue by wayspurrchen** [alex94puchades/superagent-jsonapify#12]
I realized that this library uses a `const` in the `common.js` file while breaks anything under IE11. With Webpack 1, I had to add the following to make sure the module's contents were transpiled into ES5:

```
    module: {
        loaders: [
            {
                test: /\.jsx??$/,
                loaders: [
                    babelReactLoader
                ],
                include: [
                    path.resolve(__dirname, 'src'),
                    // superagent-jsonapify has some const in it that breaks IE10
                    path.resolve(__dirname, 'node_modules/superagent-jsonapify')
                ]
                // exclude: /node_modules/
            }
        ]
    }
```

It would be nice if this module's browser support matrix could be documented in the README or have the distributed version of the module be transpiled into ES5.

**Comment by alex94puchades** [comment]
Sorry, I got so used to ES6 😅

**Comment by wayspurrchen** [comment]
Thank you! Can you publish a new version with this fix when you have a moment? :)

**Comment by ikorgik** [comment]
Hi @alex94puchades, can you please release a new version with this fix?

**Comment by alex94puchades** [comment]
@wayspurrchen @ikorgik Done, 1.4.5 has just been published.

**Comment by ikorgik** [comment]
Thanks a lot for your quick response!
